### PR TITLE
Leaf/peppacaiou/making endpoints for upvoting and downvoting

### LINKED ISSUE #26: [Primary Feature] Make Endpoints for Upvoting and Downvoing.
### User Story
As a developer, I want a convenient way to track the students' feedback towards the professors in the database.  

### Technical Tasks
- Make sure the API can have endpoints that can send upvotes and downloads to the database.

### Acceptance Criteria
- The database can accept upvotes and downvotes.

### PR DESCRIPTION
**Pull request by E-A-H62**
Tests the API endpoints that returns the professor data and the list of professor names.  Also tests the different outcomes that may occur in the endpoints.

### CODE REVIEW

**Review by ZombiMigz — APPROVED** [review]
looks good to me. well done!

**Review by GuyWhoCode — DISMISSED** [review]
Looks fine to me. ESLint errors could be removed by adding the following comment at the top of the functions in `api/sql.ts`:
`// eslint-disable-next-line @typescript-eslint/no-unused-vars`

Or this comment at the top of the file, at least temporarily:
`/* eslint-disable @typescript-eslint/no-unused-vars */`

**Comment by TonyTong112358** [comment]
do not that servertest got 0 changes

**Review by GuyWhoCode — APPROVED** [review]
Having the error be of type `unknown` is slightly concerning but understanding since Errors vary based on library. Overall looks great!

**Review by ZombiMigz — APPROVED** [review]

**Comment by TonyTong112358** [comment]
finished both : https://github.com/BroncoDirectMe/Backend/issues/26 
and : https://github.com/BroncoDirectMe/Backend/pull/35

**Pull request merged**
