### PR TITLE
Mega Merge [main <- dev]

### PR DESCRIPTION
**Pull request by wheatleyinabox**

### CODE REVIEW

**Review by PattyCakesxD — CHANGES_REQUESTED** [review]
Resolve merge conflicts - don't be afraid to double check w/ other devs if you're not 100% sure about some changes

**Comment by wheatleyinabox** [comment]
> Resolve merge conflicts - don't be afraid to double check w/ other devs if you're not 100% sure about some changes

Cool! I'm have a local clone where I'm doing working on the conflicts right now

**Review by wheatleyinabox — COMMENTED** [review]
Reviewed

**Review by GuyWhoCode — APPROVED** [review]
LGTM

**Review by PattyCakesxD — APPROVED** [review]
squash and merge, lgtm!

**Pull request merged**
